version: "3"
services:
  backend:  
    build:
      context: ./IrviQuiz.API
      dockerfile: Dockerfile
    ports:
      - "8080:5036"
    container_name: irviquiz-back

  frontend:
    build:
      context: ./IrviQuiz.Web
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    container_name: irviquiz-front
    depends_on:
      - backend
      