apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irviquiz-ingress
  namespace: irviquiz
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: quiz.yrwing.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: irviquiz-web
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: irviquiz-api
                port:
                  number: 80
