- name: Setup ArgoCD, Ingress Controller, and Application
  hosts: localhost
  tasks:

    # Configura o contexto para o AKS
    - name: Configure K8s context for AKS
      command: >
        az aks get-credentials --resource-group rg-irviquiz-dev --name aks-irviquiz-dev --overwrite-existing

    # Namespace do ArgoCD
    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: argocd
        state: present

    # Instala ArgoCD
    - name: Install ArgoCD using kubectl apply
      ansible.builtin.command:
        cmd: >
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    # Expõe ArgoCD via LoadBalancer
    - name: Patch ArgoCD service to LoadBalancer
      ansible.builtin.command:
        cmd: >
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

    # Namespace da aplicação
    - name: Create IrviQuiz namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: irviquiz
        state: present

    # Cria namespace do ingress-nginx
    - name: Create ingress-nginx namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: ingress-nginx
        state: present

    - name: Install NGINX Ingress Controller
      ansible.builtin.shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx --create-namespace \
          --set controller.service.type=LoadBalancer

    # Cria a aplicação do ArgoCD (GitOps apontando para o repositório)
    - name: Create IrviQuiz application in ArgoCD
      kubernetes.core.k8s:
        state: present
        src: files/app-irviquiz.yaml

    # Cria Service para o frontend
    - name: Create Service for IrviQuiz Web
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: irviquiz-web
            namespace: irviquiz
          spec:
            selector:
              app: irviquiz-web
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Wait for ingress-nginx controller to be ready
      ansible.builtin.command:
        cmd: >
          kubectl wait --namespace ingress-nginx
          --for=condition=ready pod
          --selector=app.kubernetes.io/component=controller
          --timeout=180s                

    # Aplica o Ingress para o frontend
    - name: Apply IrviQuiz Ingress
      kubernetes.core.k8s:
        state: present
        src: files/ingress-irviquiz.yaml
