- name: Setup ArgoCD, Ingress Controller, and Application
  hosts: localhost
  tasks:

    - name: Configure K8s context for AKS
      command: >
        az aks get-credentials --resource-group rg-irviquiz-dev --name aks-irviquiz-dev --overwrite-existing

    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: argocd
        state: present

    - name: Install ArgoCD using kubectl apply
      ansible.builtin.command:
        cmd: >
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Patch ArgoCD service to LoadBalancer
      ansible.builtin.command:
        cmd: >
          kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'

    - name: Create IrviQuiz namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: irviquiz
        state: present

    - name: Create ingress-nginx namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: ingress-nginx
        state: present

    - name: Install NGINX Ingress Controller
      ansible.builtin.shell: |
       helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
       helm repo update
        helm install ingress-nginx ingress-nginx/ingress-nginx \
        --namespace ingress-nginx --create-namespace \
        --set controller.service.type=LoadBalancer \
        --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"="/healthz" \
        --set controller.service.externalTrafficPolicy=Cluster

    - name: Create IrviQuiz application in ArgoCD
      kubernetes.core.k8s:
        state: present
        src: files/app-irviquiz.yaml

    - name: Create Service for IrviQuiz Web
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: irviquiz-web
            namespace: irviquiz
          spec:
            selector:
              app: irviquiz-web
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Wait for ingress-nginx controller to be ready
      ansible.builtin.command:
        cmd: >
          kubectl wait --namespace ingress-nginx
          --for=condition=ready pod
          --selector=app.kubernetes.io/component=controller
          --timeout=180s                

    - name: Apply IrviQuiz Ingress
      kubernetes.core.k8s:
        state: present
        src: files/ingress-irviquiz.yaml
